name: Publish

on:
  push:
    tags: 
      - *

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Test
        run: /bin/bash ./.ci/test.sh
      - name: Build Docker Image
        run: /bin/bash ./.ci/buildDockerImage.sh
        env:
          TAG: ${{ steps.vars.outputs.tag }}
      - name: Publish Docker Image
        run: /bin/bash ./.ci/publishDockerImage.sh
        env:
          TAG: ${{ steps.vars.outputs.tag }}
